"""empty message

Revision ID: 0eb8f3946e24
Revises: 456a945560f6
Create Date: 2018-11-02 16:01:28.606521

"""

# revision identifiers, used by Alembic.
revision = '0eb8f3946e24'
down_revision = '456a945560f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('companyname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_companyname'), 'users', ['companyname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_companyname'), table_name='users')
    op.drop_column('users', 'companyname')
    # ### end Alembic commands ###
