"""empty message

Revision ID: 187aae8b161b
Revises: 8f397bb929d8
Create Date: 2018-11-08 10:42:27.722615

"""

# revision identifiers, used by Alembic.
revision = '187aae8b161b'
down_revision = '8f397bb929d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
