"""empty message

Revision ID: 34d3d10dd860
Revises: 0eb8f3946e24
Create Date: 2018-11-02 16:06:09.841091

"""

# revision identifiers, used by Alembic.
revision = '34d3d10dd860'
down_revision = '0eb8f3946e24'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
