"""empty message

Revision ID: 3b36ecb33e27
Revises: dedd086c6b3c
Create Date: 2018-11-02 21:17:41.041273

"""

# revision identifiers, used by Alembic.
revision = '3b36ecb33e27'
down_revision = 'dedd086c6b3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
