"""empty message

Revision ID: 504814cb4add
Revises: c7e80bb6ca65
Create Date: 2018-11-22 11:29:46.741122

"""

# revision identifiers, used by Alembic.
revision = '504814cb4add'
down_revision = 'c7e80bb6ca65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
