"""empty message

Revision ID: 934595c79b74
Revises: d8e5420b4ab5
Create Date: 2018-11-08 11:21:17.584824

"""

# revision identifiers, used by Alembic.
revision = '934595c79b74'
down_revision = 'd8e5420b4ab5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
