"""empty message

Revision ID: c7e80bb6ca65
Revises: 934595c79b74
Create Date: 2018-11-14 16:39:10.497009

"""

# revision identifiers, used by Alembic.
revision = 'c7e80bb6ca65'
down_revision = '934595c79b74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
