"""empty message

Revision ID: d8e5420b4ab5
Revises: 187aae8b161b
Create Date: 2018-11-08 11:21:13.259453

"""

# revision identifiers, used by Alembic.
revision = 'd8e5420b4ab5'
down_revision = '187aae8b161b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
