"""empty message

Revision ID: dedd086c6b3c
Revises: 34d3d10dd860
Create Date: 2018-11-02 21:08:08.454330

"""

# revision identifiers, used by Alembic.
revision = 'dedd086c6b3c'
down_revision = '34d3d10dd860'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
